version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # - DATABASE_URL=postgres//
      - DATABASE_URL=postgresql+asyncpg://violet:toorpass@localhost:54320/url_shortener
    volumes:
      - .:/app
      - /app/__pycache__
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
